export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FILTER_BY_DIET = 'FILTER_BY_DIET';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const RESET_URL = 'RESET_URL';
export const DELETE_DIET_FILTER = 'DELETE_DIET_FILTER';
export const DELETE_CATEGORY_FILTER = 'DELETE_VATEGORY_FILTER';
