export const SET_ACTIVE_DATA = 'SET_ACTIVE_DATA';
export const SET_SHOP_DATA = 'SET_SHOP_DATA';
export const RESET_ACTIVE_DATA = 'RESET_ACTIVE_DATA';
export const SET_DIETS_DATA = 'SET_DIETS_DATA';
export const SET_CATEGORIES_DATA = 'SET_CATEGORIES_DATA';
