export const SHOW_PRODUCT_MODAL = 'SHOW_PRODUCT_MODAL';
export const CLOSE_PRODUCT_MODAL = 'CLOSE_PRODUCT_MODAL';
export const SHOW_CATEGORIES_MODAL = 'SHOW_CATEGORIES_MODAL';
export const CLOSE_CATEGORIES_MODAL = 'CLOSE_CATEGORIES_MODAL';
export const SHOW_BRANDS_MODAL = 'SHOW_BRANDS_MODAL';
export const CLOSE_BRANDS_MODAL = 'CLOSE_BRANDS_MODAL';

export const closeBrandsModal = { type: CLOSE_BRANDS_MODAL };
export const showBrandsModal = { type: SHOW_BRANDS_MODAL };
